version: '2'

services:

  stat-database:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=stat
      - POSTGRES_PASSWORD=stat
    ports:
     - "5432:5432"
    volumes:
     - /home/all/db-data/stat:/var/lib/postgresql/data

  stat-migrate:
    build:
      ./migrate
    environment:
      - STAT_DB_HOST=stat-database
      - STAT_DB_PORT=5432
      - STAT_DB_USER=stat
      - STAT_DB_PASSWORD=stat
      - STAT_DB_NAME=stat
    depends_on:
      - stat-database

  stat:
    build:
      .
    ports:
      - "9090:8080"
    depends_on:
      - stat-database

#  stat-grafana:
#    image: grafana/grafana
#    ports:
#      - "3000:3000"